#!/bin/sh /etc/rc.common
# Copyright (C) 2012 Patrick Grimm

START=99

load_uci() {
	/usr/bin/linknxloaddata.lua
#	/usr/bin/linknxwriterule.lua
}

start() {
	sleep 3
	/etc/init.d/linknx stop
	mkdir -p /var/lib/linknx/persist
	mkdir -p /var/lib/linknx/rrd
	mkdir -p /var/lib/linknx/tmp
	uci set linknx.args.conf='/var/lib/linknx/linknx.xml'
	#if [ "$(uci -q get linknx.@daemon[0].log)" == 1 ] ; then
	#	uci set linknx.args.options='--daemon=/var/lib/linknx/linknx.log --pid-file=/var/run/linknx.pid'
	#else
	#	uci set linknx.args.options='--daemon=/dev/null --pid-file=/var/run/linknx.pid'
	#fi
	uci commit
	rm -f /var/lib/linknx/linknx.xml
	rm -f /var/run/linknx
	ln -s /etc/linknx/config.socket.xml /var/lib/linknx/linknx.xml &>/dev/null
	/etc/init.d/linknx restart
	sleep 3
	load_uci &>/dev/null
	chmod 777 /var/run/linknx
}

reload() {
	load_uci
}

restart() {
	stop
	start
}

stop() {
	/etc/init.d/linknx stop
}
