#!/bin/sh /etc/rc.common
# Copyright (C) 2012 Patrick Grimm

START=99
USE_PROCD=1
SERVER_BIN=/usr/sbin/linknxsubsscribemqtt.lua

load_uci() {
	/usr/bin/linknxloaddata.lua
}

start_service() {
	load_uci
	procd_open_instance
	procd_set_param command "$SERVER_BIN"
	procd_set_param respawn
	procd_set_param stderr 1
	procd_open_trigger
	procd_add_raw_trigger "interface.*" 2000 /etc/init.d/linknx-uci restart
	config_files="$(ls /etc/config/knx*)"
	for file in $config_files ; do
		if [ -f "$file" ] ; then
			chmod 644 $file
			procd_add_config_trigger "config.change" "$file" /etc/init.d/linknx-uci restart
		fi
	done
	procd_close_trigger
	procd_close_instance
}

reload_service() {
	load_uci
}

restart_service() {
	stop
	/etc/init.d/linknx restart
	start
}
