#!/bin/sh

. /lib/functions.sh

uci_add linknx station ; cfg="$CONFIG_SECTION"
uci_set linknx $cfg tagname 'linknx'
uci_set linknx $cfg enable '1'
uci_set linknx $cfg description 'KNX Bus'
#Save
uci_commit linknx

uci_set knxd args client_addrs '2.2.20:10'
uci_set knxd args url 'ip:224.0.23.12'
uci_set knxd args eibaddr '0.0.100'
uci_set knxd args Discovery '0'
uci_set knxd args Tunnelling '0'
uci_set knxd args Routing '0'
uci_commit knxd
