#!/bin/sh

[ -f "${IPKG_INSTROOT}/etc/config/ucitrack" ] && \
[ "$(uci get ucitrack.@linknx_group[0].affects 2>/dev/null)" != "linknx" ] && \
uci batch <<-EOF >/dev/null 2>/dev/null
        add ucitrack linknx_group
        set ucitrack.@linknx_group[-1].exec="/usr/bin/linknx-uci-event.sh"
        set ucitrack.@linknx_group[-1].affects=linknx
        commit ucitrack
EOF


#cp /www/linknx.html /www/index.html
/usr/bin/linknx-uci-event.sh
grep -q "linknx-uci-event.sh" /etc/crontabs/root || echo "*/30 * * * * /usr/bin/linknx-uci-event.sh clean" >> /etc/crontabs/root

mkdir /home
##(echo n; echo p; echo 3; echo 250; echo; echo w) | fdisk /dev/sda

hostname=$(cat /proc/sys/kernel/hostname)

echo '#name         #type        #domain  #port  #text' > /etc/mDNSResponder.conf
echo "$hostname"'   _http._tcp   local.   80     "txtvers=1" "path=/linknx.html" "note=LINKNX Control"' >> /etc/mDNSResponder.conf
echo "$hostname"'   _http._tcp   local.   80     "txtvers=1" "path=/cgi-bin/luci" "note=LuCI"' >> /etc/mDNSResponder.conf

