#!/bin/sh /etc/rc.common
# Copyright (C) 2016 Patrick Grimm

START=50
USE_PROCD=1
SERVER="ubus-linknx"
SERVER_BIN="/usr/sbin/ubus-linknx"
SERVER_ARGS="-r linknxws"

start_service() {
	procd_open_instance
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param command "$SERVER_BIN"
	procd_append_param command -r linknxws
	procd_close_instance
}
