#!/bin/sh /etc/rc.common
# Copyright (C) 2016 Patrick Grimm

START=45
USE_PROCD=1
SERVER="ws-mirror-server"
SERVER_BIN="/usr/sbin/ws-mirror-server"
SERVER_UBUS="ws-mirror-server-ubus"
SERVER_UBUS_BIN="/usr/sbin/ws-mirror-server-ubus"
PX5G_BIN="/usr/sbin/px5g"

generate_keys_pem() {
	local cfg="$1"
	local key="$2"
	local crt="$3"
	local days bits country state location commonname

	config_get days       "$cfg" days
	config_get bits       "$cfg" bits
	config_get country    "$cfg" country
	config_get state      "$cfg" state
	config_get location   "$cfg" location
	config_get commonname "$cfg" commonname

	[ -x "$PX5G_BIN" ] && {
		$PX5G_BIN selfsigned -pem \
			-days ${days:-730} -newkey rsa:${bits:-1024} -keyout "${UHTTPD_KEY}.new" -out "${UHTTPD_CERT}.new" \
			-subj /C="${country:-DE}"/ST="${state:-Preussen}"/L="${location:-Berlin}"/CN="${commonname:-OpenWrt}"
		sync
		mv "${UHTTPD_KEY}.new" "${UHTTPD_KEY}"
		mv "${UHTTPD_CERT}.new" "${UHTTPD_CERT}"
	}
}

check_keys()
{
	UHTTPD_CERT=""
	UHTTPD_KEY=""
	local cfg="$1"

	config_get UHTTPD_KEY  "$cfg" key  /etc/uhttpd.key
	config_get UHTTPD_CERT "$cfg" cert /etc/uhttpd.crt

	grep -q CERT "$UHTTPD_CERT" || {
		config_foreach generate_keys_pem cert
	}
	grep -q KEY "$UHTTPD_KEY" || {
		config_foreach generate_keys_pem cert
	}
	procd_append_param command -k "$UHTTPD_KEY"
	procd_append_param command -c "$UHTTPD_CERT"
}

start_service() {
	procd_open_instance
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param command "$SERVER_BIN"
	procd_append_param command -x linknxws
	procd_append_param command -p 7681
	procd_append_param command --ssl
	config_load uhttpd
	config_foreach check_keys uhttpd
	procd_close_instance

	procd_open_instance
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param command "$SERVER_UBUS_BIN"
	procd_append_param command 127.0.0.1
	procd_append_param command -r linknx
	procd_append_param command -p 7681
	procd_append_param command --ssl
	procd_close_instance
}
