#!/bin/sh

[ -f "${IPKG_INSTROOT}/etc/config/ucitrack" ] && \
[ "$(uci get ucitrack.@eibd[0] 2>/dev/null)" != "eibd" ] && \
uci batch <<-EOF >/dev/null 2>/dev/null
	add ucitrack eibd
	set ucitrack.@eibd[-1].init="/etc/init.d/eibd"
	set ucitrack.@eibd[-1].affects="linknx"
	commit ucitrack
EOF

uci batch <<-EOF >/dev/null 2>/dev/null
	add network route
	set network.@route[-1].gateway="0.0.0.0"
	set network.@route[-1].interface="lan"
	set network.@route[-1].target="224.0.23.12"
	commit network
EOF

