#!/bin/sh /etc/rc.common
# Copyright (C) 2012 Patrick Grimm

START=90
SERVER="eibd"
SERVER_ARGS=""

append_bool() {
	local section="$1"
	local option="$2"
	local value="$3"
	local _loctmp
	local default="$4"
	config_get_bool _loctmp "$section" "$option"
	[ -z "$_loctmp" ] && _loctmp="$default"
	[ "$_loctmp" -gt 0 ] && append args "--$value"
}

append_parm() {
	local section="$1"
	local option="$2"
	local switch="$3"
	local _loctmp
	local default="$4"
	config_get _loctmp "$section" "$option"
	[ -z "$_loctmp" ] && _loctmp="$default"
	[ -z "$_loctmp" ] && return 0
	append args "--$switch=$_loctmp"
}

startinterface() {
	args=""
	local cfg="$1"
	local interface
	local pidfile
	config_get pidfile "$cfg" "pidfile" 
	[ -z "$pidfile" ] && pidfile="/var/run/eibd.pid"
	#append args "--pid-file=$pidfile"
	#Begin For ETS3
	append_bool "$cfg" Discovery "Discovery" 1
	append_bool "$cfg" Server "Server" 1
	append_bool "$cfg" Tunnelling "Tunnelling" 1
	#End For ETS3
	append_parm "$cfg" listentcp "listen-tcp" "6720"
	append_parm "$cfg" listenlocal "listen-local" "/var/run/eibd.sock"
	append_parm "$cfg" eibaddr "eibaddr" "0.0.1"
#	append_parm "$cfg" daemon "daemon" "/tmp/eibd.log"
#	append args "--daemon"
	append_parm "$cfg" trace "trace" # "7"
	append_parm "$cfg" error "error" # "5"
	config_get url "$cfg" "url"
	case $url in
	    usb*)
		local usbdev="$(findknxusb | grep "device: [0-9]:[0-9]:[0-9]:[0-9]"| cut -d ' ' -f 2)"
		[ -z "$usbdev" ] && return 0 || append args "usb:$usbdev"
	    ;;
	    ip) append args "ip:" ;;
	    *) append args "$url" ;;
	esac

	start-stop-daemon -S -x $SERVER \
		-p ${pidfile} \
		-m -b -- ${args}
}

stopinterface() {
	local pidfile
	config_get pidfile "$cfg" "pidfile" 
	[ -z "$pidfile" ] && pidfile="/var/run/eibd.pid"
	[ -f ${pidfile} ] && {
	start-stop-daemon -K -q -n $SERVER \
		-p ${pidfile} -s TERM
	}
}

start() {
	config_load eibd
	config_foreach startinterface eibinterface
}

stop() {
	config_load eibd
	config_foreach stopinterface eibinterface
}

restart() {                                                                                           
        stop                                                                                          
        sleep 1                                                                                       
        start                                                                                         
}

