#!/bin/sh /etc/rc.common
# Copyright (C) 2012 Patrick Grimm

START=95
SERVER="linknx"
SERVER_BIN="/usr/sbin/linknx"
SERVER_ARGS="--config=/etc/linknx/config.socket.xml  --pid-file=/var/run/linknx.pid -d"

load_uci() {
	/usr/bin/linknxloaddata.lua
#	/usr/bin/linknxwriterule.lua
}

start() {
	mkdir -p /var/lib/linknx/persist
	mkdir -p /var/lib/linknx/rrd
	mkdir -p /var/lib/linknx/tmp
	uci set linknx.args.conf='/etc/linknx/config.socket.xml'
	uci commit
	#rm /var/lib/linknx/linknx.xml
	#ln -s /etc/linknx/config.socket.xml /var/lib/linknx/linknx.xml
	#rm /var/run/linknx.sock
	#ln -s /tmp/xmlserver.sock /var/run/linknx.sock
	/etc/init.d/linknx restart
	sleep 3
	load_uci
	chmod 777 /var/run/linknx.sock
}

reload() {
	load_uci
}

restart() {
	stop
	start
}

stop() {
	/etc/init.d/linknx stop
}
