#!/bin/sh /etc/rc.common
# Copyright (C) 2012 Patrick Grimm

START=95
SERVER="linknx"
SERVER_BIN="/usr/sbin/linknx"
SERVER_ARGS="--config=/etc/linknx/config.socket.xml  --pid-file=/var/run/linknx.pid -d"

load_uci() {
	/usr/bin/linknxloaddata.lua
#	/usr/bin/linknxwriterule.lua
}


boot() {
	(
	sleep 40
	start
	) >/dev/null 2>&1 &
}

start() {
	mkdir -p /var/lib/linknx/persist
	mkdir -p /var/lib/linknx/rrd
	mkdir -p /var/lib/linknx/tmp
	#rm /var/lib/linknx/linknx.xml
	#ln -s /etc/linknx/config.socket.xml /var/lib/linknx/linknx.xml
	#rm /var/run/linknx.sock
	#ln -s /tmp/xmlserver.sock /var/run/linknx.sock
	start-stop-daemon -S -x $SERVER_BIN \
		-p /var/run/${SERVER}.pid \
		-m -b -- ${SERVER_ARGS}
	sleep 5
	load_uci
	chmod 777 /var/run/linknx.sock
}

reload() {
	load_uci
}

restart() {
	stop
	start
}

stop() {
	[ -f /var/run/${SERVER}.pid ] && {
		start-stop-daemon -K -q -n ${SERVER_BIN##*/} \
			-p /var/run/${SERVER}.pid -s TERM

		rm -f /var/run/${SERVER}.pid
	}
}

